// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMkYJuwMAIMP3gkcLGqH67sJEM0mYEowk',
    appId: '1:356595617520:android:edb3303db5cadd4a453c35',
    messagingSenderId: '356595617520',
    projectId: 'groupchatapp-632c2',
    databaseURL: 'https://groupchatapp-632c2-default-rtdb.firebaseio.com',
    storageBucket: 'groupchatapp-632c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD71wSLZepvuRJdsO5VMJ90hY_8BULzWsw',
    appId: '1:356595617520:ios:44b9c5c208005e60453c35',
    messagingSenderId: '356595617520',
    projectId: 'groupchatapp-632c2',
    databaseURL: 'https://groupchatapp-632c2-default-rtdb.firebaseio.com',
    storageBucket: 'groupchatapp-632c2.appspot.com',
    androidClientId: '356595617520-kihnbao5719opfhkgsjle4aseomr9d90.apps.googleusercontent.com',
    iosClientId: '356595617520-for98n7ab5pua1cm9b7ali9ppreinuq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommProject',
  );

}